### ISSUE TITLE
Add an idempotent `ensure` subcommand

### ISSUE THREAD

**Issue by kevinjqiu** [alphabetum/hosts#4]
e.g.,

```
hosts ensure 192.168.0.1 gateway.example.com
```

If the entry already exists in the hosts file then do nothing, add it otherwise.

**Comment by xwmx** [comment]
Thanks for the suggestion, Kevin!

The current `add` subcommand has an existing guard against duplicate entries ([hosts#L704](https://github.com/alphabetum/hosts/blob/master/hosts#L704)). When the user attempts at add a duplicate entry using the `add` subcommand, `hosts` exits with a status of `1` and displays an error message stating "Duplicate address/host combination, /etc/hosts unchanged." The existing approach is intended to provide the user with feedback and an error exit status that they can handle according to their needs within their own shell environment or program.

The difference between the existing behavior of `add` and the proposed `ensure` behavior is that a duplicate entry would not trigger an error message and exit the program, instead exiting with a `0` status. If this functionality was to be added, suppressing the error with a flag to `add` (e.g., `hosts add --ensure`) seems like it would be the most straightforward way to add this kind of functionality since the duplicate guard already exists in `add`.

My initial inclination is to just retain the existing `add` functionality since the error message and return status are useful information for users, and they can handle or suppress the error outside of the `hosts` program as needed.

Is the current duplication guard in `add` sufficient?

**Comment by kevinjqiu** [comment]
Thank for the response @alphabetum.  The existing guard should be sufficient for my use case.  Cheers!

**Comment by xwmx** [comment]
Awesome. Thanks for bringing this up! It prompted me to add [some missing tests for this functionality](https://github.com/alphabetum/hosts/commit/6b72e51651e1aba026a76463ace1cf7313c1b3c1). :-)
