### ISSUE TITLE
The message show when remove entry.

### ISSUE THREAD

**Issue by time-kmitl** [alphabetum/hosts#5]
Hello,

Firstly, Thank you for saving the time to manage the host file also when I remove an entry that shows message "sed: can't read : No such file or directory".

**Comment by xwmx** [comment]
Hi @time-kmitl, thank you for the bug report! This error message was due to platform issues with the `sed` arguments. A platform check has been added to help ensure that the arguments are handled properly on each platform. Let me know if you run into any further issues after updating to version 3.1.1.
